image: 
  - Visual Studio 2017

platform:
  - x86

environment:
  APPVEYOR_RDP_PASSWORD: Vue#2009
  matrix:
    - nodejs_version: '10'
  GH_TOKEN:
    secure: nHwMgMQEtRz4aOFCd55jOo41s9dXD2S4m9Tf0hohiQFQofo2mJ3KThNyL5HBg/Eb
  ACCESS_TOKEN:
    secure: nHwMgMQEtRz4aOFCd55jOo41s9dXD2S4m9Tf0hohiQFQofo2mJ3KThNyL5HBg/Eb

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
  - npm install -g yarn
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

matrix:
  fast_finish: true

shallow_clone: true

test_script:
  - yarn test:unit

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"
  - '%APPDATA%\npm-cache'

build_script:
  - yarn lint
  - yarn electron:build

skip_tags: true

artifacts:
  - path: dist_electron\*.exe
    name: bin
